language: dart

dart:
  - dev

dart_task:
  # Tests are not passing at the moment – investigating
  #- test
  - dartanalyzer
  - dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache
